# Generated by Django 4.0.3 on 2022-04-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TM_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesmodel',
            name='user_name',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
