# Generated by Django 4.0.3 on 2022-04-08 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TM_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesmodel',
            name='in_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='timesmodel',
            name='out_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='timesmodel',
            name='pere',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='timesmodel',
            name='user_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='timesmodel',
            name='in_time',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='timesmodel',
            name='out_time',
            field=models.TextField(),
        ),
    ]
