# Generated by Django 4.0.3 on 2022-04-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TM_app', '0003_alter_timesmodel_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesmodel',
            name='in_time',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='timesmodel',
            name='out_time',
            field=models.TextField(),
        ),
    ]
