# Generated by Django 4.0.3 on 2022-04-05 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TM_app', '0004_alter_timesmodel_in_time_alter_timesmodel_out_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesmodel',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 5)),
        ),
    ]
