# Generated by Django 4.0.3 on 2022-04-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TM_app', '0005_timesmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesmodel',
            name='date',
            field=models.DateField(),
        ),
    ]
